server:
  port: 8000
  servlet:    
      encoding:      
        charset: UTF-8
        enabled: true
        force: true
        force-request: true
        force-response: true
  tomcat:    
    uri-encoding: UTF-8

spring:  
    mvc:    
      view:      
        prefix: /WEB-INF/views/
        suffix: .jsp
    security:    
      user:      
        name: test
        password: 1234
      oauth2:      
        client:        
          registration:
            google:
              client-id: 441276680824-6ebgmo4a9on3ds2o1u5qerogjqmksoh6.apps.googleusercontent.com
              client-secret: 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
              scope:            
              - email
              - profile   
            naver:
              client-id: 7WpbBtMDfQwKb4R6qt7x
              client-secret: ZDsjH6dpCa
              scope:            
              - email
              - name
              - mobile
              client-name: Naver
              authorization-grant-type: authorization_code
              redirect-uri: http://localhost:8000/login/oauth2/code/naver
          provider:          
            naver:
              authorization-uri: https://nid.naver.com/oauth2.0/authorize
              token-uri: https://nid.naver.com/oauth2.0/token
              user-info-uri: https://openapi.naver.com/v1/nid/me
              user-name-attribute: response #회원정보를 json으로 전달할 때 response라는 KEY값으로 데이터를 전달.  datasource:    driver-class-name: org.mariadb.jdbc.Driver
    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
#      url: jdbc:mariadb://database-study.cs41knlyokk5.ap-northeast-2.rds.amazonaws.com:3306/project_20220113_04?useUnicode=true
      url: jdbc:mariadb://121.175.150.249:3306/project_20220113_04?useUnicode=true
      username: tp220113_04
      password: 3637
    
mybatis:  
  mapper-locations:  
  - /mappers/*.xml
  
file :
  path: C:\Spring\workspace\jobkoreaImg\
#  path: /home/ubuntu/Spring/workspace/jobkoreaImg/

test:
  filename: test_file.txt  

